title: "Blogs"
author: "Chirag Gupta"
description: "Golang & Cloud-Native"   # show on social previews (Twitter/LinkedIn)

# URL settings - choose depending on user-site vs project-site:
url: "https://chiragg6.github.io"      # <-- your user site
# baseurl: "/my-tech-blogs"            # <-- uncomment if this is a project site

# Contact / social (minima reads these)
email: "chiragg6@gmail.com"
# twitter_username: ""                   # without @ (optional)
github_username: "chiragg6"
linkedin_username: "chirag-gupta93"    # username preferred (not full URL)

theme: minima

# Markdown / syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false

# Plugins allowed on GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# If you prefer titles taken from the first heading in each post
titles_from_headings:
  strip_title: true
  collections: true

# Permalink format (pretty URLs)
permalink: /:year/:month/:day/:title/

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: post
    values:
      layout: post
      tags: Other

# Files/dirs to exclude from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Optional: enable pagination (requires jekyll-paginate plugin)
# paginate: 10
# paginate_path: "/page:num/"
